retriever:
  framework: "langchain"  # or "haystack"
  params:
    embedding_model: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
    device: "cuda"  # Use GPU
  document_store:
    type: "faiss"  # Options: "faiss" or "pinecone" or "elasticsearch"
    params:
      persistent: true  # Set to true to enable saving/loading the index for FAISS
      embedding_model: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
      # Pinecone-specific configuration (only applies if type is "pinecone")
      api_key: "your_pinecone_api_key"  # Replace with your Pinecone API key
      index_name: "your_pinecone_index_name"  # Replace with your Pinecone index name



llm:
  provider: "deepseek"  # or "openai"
  params:
    api_key: "${sk-60abf91dbc1b4b3991cfa5362f0e4c1b}"
    model: "deepseek-r1:14b"
    mode: "local"
    temperature: 0.3
    max_tokens: 512
    stream: False

hash_store:
  type: "sqlite"  # Options: "sqlite", "redis", "mongodb", etc.
  params:
    db_path: "path/to/your/hash_store.db"  # Replace with your database file path


scraper:
  type: "iranhotelonline"  # or "yelp"
  params:
    api_key: "your-scraper-api-key"  # Example key for scraper usage